# Generated by Django 4.1.2 on 2022-11-03 05:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_tax'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderproduct',
            name='color',
        ),
        migrations.RemoveField(
            model_name='orderproduct',
            name='size',
        ),
    ]
